### ISSUE TITLE
Package & Target name conflicts with `SDWebImage/libwebp-Xcode`

### ISSUE THREAD

**Issue by daniel-l2** [awxkee/avif.swift#1]
Conflicting package: https://github.com/SDWebImage/libwebp-Xcode

We face the error below when trying to use two packages together since both of them provide target and package named `libwebp`.

```
xcodebuild: error: Could not resolve package dependencies: multiple products named 'libwebp' in: 'libwebp-ios', 'libwebp-xcode'

xcodebuild: error: Could not resolve package dependencies:
 multiple targets named 'libwebp' in: 'libwebp-ios', 'libwebp-xcode'; consider using the `moduleAliases` parameter in manifest to provide unique names
```

To resolve this, https://github.com/awxkee/libwebp-ios/pull/1 should be merged first and then update depedencies in this repository.

**Comment by awxkee** [comment]
> Conflicting package: https://github.com/SDWebImage/libwebp-Xcode
> 
> We face the error below when trying to use two packages together since both of them provide target and package named `libwebp`.
> 
> ```
> xcodebuild: error: Could not resolve package dependencies: multiple products named 'libwebp' in: 'libwebp-ios', 'libwebp-xcode'
> 
> xcodebuild: error: Could not resolve package dependencies:
>  multiple targets named 'libwebp' in: 'libwebp-ios', 'libwebp-xcode'; consider using the `moduleAliases` parameter in manifest to provide unique names
> ```
> 
> To resolve this, [awxkee/libwebp-ios#1](https://github.com/awxkee/libwebp-ios/pull/1) should be merged first and then update depedencies in this repository.

I made the changes. Try out `1.4.8` version

**Comment by daniel-l2** [comment]
Thank you for your support :)
