### ISSUE TITLE
Conflicting types for 'SharpYuvGammaToLinear/Gamma' due to dependency conflict

### ISSUE THREAD

**Issue by Zedd0202** [awxkee/avif.swift#2]
I am encountering a problem related to conflicting types for the function 'SharpYuvGammaToLinear/Gamma' while using the avif.swift library. 
The conflict seems to stem from conflicting dependencies involving the libwebp libraries.

### The dependency chain is as follows:

- The avif.swift library relies on libwebp-ios.
- libwebp-ios has a dependency on libwebp.
- Additionally, there is another library, libwebp-Xcode (https://github.com/SDWebImage/libwebp-Xcode), which also depends on libwebp.
This dependency structure results in a conflict regarding the 'SharpYuvGammaToLinear/Gamma' function, leading to the mentioned error.

### Steps to Reproduce:

Include avif.swift and libwebp-ios(https://github.com/SDWebImage/libwebp-Xcode) as dependencies in an Xcode project.
<img width="842" alt="스크린샷 2023-10-16 오후 3 33 59" src="https://github.com/awxkee/avif.swift/assets/24826569/5c4e70e7-5b45-4c2b-aca5-5417ba264fc6">

I'd like to hear your opinion on what to do in times like this.

**Comment by awxkee** [comment]
I've updated the 'libwebp-ios'. Try update this to '1.1.1' version. It should resolve this issue. However, if you will face the 'duplicate symbol exception' after this you may be still need to link one of the libraries dynamically instead of static to the project, if you are using a static linking.

**Comment by Zedd0202** [comment]
It seems to be working fine. Thank you so much for the quick assistance.

By the way, how do I use **animated** AVIF? I followed the usage, but it's not animating as expected.

I use it like this: `let image: UIImage = try animatedDecoder.getImage(frame: 1)`, it seems to be causing the issue. (frame: 1) 
If I want to play an animated AVIF like this one: https://colinbendell.github.io/webperf/animated-gif-decode/6.avif, what should I do?"

**Comment by awxkee** [comment]
> I use it like this: `let image: UIImage = try animatedDecoder.getImage(frame: 1)`, it seems to be causing the issue. (frame: 1)

Hi, I tried your image and do not see any issues with this one.

You may try this snipped ( do not use this in production it is very simple example) 
`
import avifc
   Task(priority: .high) {
            let animationAvifUrl = Bundle.main.url(forResource: "animation_6", withExtension: "avif")!
            var data = try! Data(contentsOf: animationAvifUrl)
            let animationDecoder = AVIFAnimatedDecoder(data: data)!
            let framesCount = animationDecoder.framesCount()
            var currentFrame = framesCount
            while (true) {
                if currentFrame >= framesCount {
                    currentFrame = 0
                }
                let frameDuration = animationDecoder.frameDuration(currentFrame)
                let frame = animationDecoder.getImage(currentFrame)
                await MainActor.run {
                    animationImage = frame
                }
                print("\(frameDuration)")
                try await Task.sleep(nanoseconds: NSEC_PER_MSEC * UInt64(frameDuration))
                currentFrame += 1
            }
        }
`
Link to the [gist](https://gist.github.com/awxkee/247e81624c5492e1c5d28122a55a5218)
The main algorithm is you have to take frames count, decode the current frame ( 0 for initial), take a frame duration, send a frame to a renderer and and repeat until frames left, then set current frame to 0 and repeat again (forever loop). You may adjust decoding time to a frame duration, prefetch, caching frames and etc as you needed.

**Comment by awxkee** [comment]
Also if you are already using SDWebImage or others image displaying libraries it may offer a protocol with already prebuilt these methods

**Comment by awxkee** [comment]
Like this [one](https://gist.github.com/awxkee/fb5380ff7588494cf39728f29f78622b)

I just created this and never tried. But this should be like this one

**Comment by Zedd0202** [comment]
I'll try following the gist. Thank you once again for your help.

++ Could you let me know how to retrieve the `loop count` for AVIF? It seems like there are properties like `kCGImagePropertyGIFLoopCount` and `kCGImagePropertyAPNGLoopCount`, but it appears that AVIF doesn't have those. Thank you.

**Comment by awxkee** [comment]
> I'll try following the gist. Thank you once again for your help.
> 
> ++ Could you let me know how to retrieve the `loop count` for AVIF? It seems like there are properties like `kCGImagePropertyGIFLoopCount` and `kCGImagePropertyAPNGLoopCount`, but it appears that AVIF doesn't have those. Thank you.

I've added a `loopCount` property in `AnimatedDecoder` in new version. For some reason I thought it should be always infinity.
