### ISSUE TITLE
Issue in LogarithmicToneMapper

### ISSUE THREAD

**Issue by BenShutt** [awxkee/avif.swift#3]
Please see the attached Xcode build error when using the `master` branch (April 8th 2024).
Changing from `log10f_c` to `log10f` works on my machine.

Versions:
* Machine: Macbook Pro 2019 - 2.6 GHz 6-Core Intel Core i7
* Swift version: 5.10
* Xcode Version: 15.3

![Screenshot 2024-04-08 at 15 56 45](https://github.com/awxkee/avif.swift/assets/57952587/6f948a31-d3fc-4ce8-95f0-4f0f68fe437b)

**Comment by awxkee** [comment]
My mistake, it function has deleted. Please, try update to the latest version from master

**Comment by BenShutt** [comment]
It now works for me! 🙌 
Really grateful for how quickly you fixed this @awxkee, thank you.

**Comment by awxkee** [comment]
Your welcome!
